# Generated by Django 4.2.27 on 2025-12-06 16:14

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailimages", "0027_image_description"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("hero_title", models.CharField(blank=True, max_length=255)),
                ("hero_subtitle", models.CharField(blank=True, max_length=255)),
                (
                    "hero_cta_text",
                    models.CharField(blank=True, default="Shop Now", max_length=100),
                ),
                ("hero_cta_link", models.URLField(blank=True)),
                (
                    "featured_title",
                    models.CharField(
                        blank=True, default="Featured Products", max_length=255
                    ),
                ),
                ("featured_description", wagtail.fields.RichTextField(blank=True)),
                (
                    "about_title",
                    models.CharField(
                        blank=True, default="About LUVORA", max_length=255
                    ),
                ),
                ("about_content", wagtail.fields.RichTextField(blank=True)),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={"verbose_name": "Home Page",},
            bases=("wagtailcore.page",),
        ),
    ]
